#!/usr/bin/env python3
"""
Web-based Setup UI for AI Customer Care Agent
Provides a browser-based interface for configuration and deployment
"""

from flask import Flask, render_template, request, jsonify, send_from_directory
import os
import subprocess
import json
import secrets

app = Flask(__name__, 
            template_folder='setup_ui/templates',
            static_folder='setup_ui/static')

CONFIG_FILE = '.env'
CONFIG_EXAMPLE = '.env.example'

def load_current_config():
    """Load current configuration from .env file"""
    config = {}
    if os.path.exists(CONFIG_FILE):
        with open(CONFIG_FILE, 'r') as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith('#') and '=' in line:
                    key, value = line.split('=', 1)
                    config[key] = value
    return config

def save_config(config_data):
    """Save configuration to .env file"""
    with open(CONFIG_FILE, 'w') as f:
        f.write("# AI Customer Care Agent Configuration\n")
        f.write("# Generated by Web Setup UI\n\n")
        
        # AI Model
        ai_model = config_data.get('ai_model', 'local')
        f.write("# AI MODEL PROVIDER\n")
        f.write(f"AI_MODEL={ai_model}\n\n")
        
        # Server Base URL
        server_url = config_data.get('server_url', '')
        if server_url:
            f.write("# SERVER CONFIGURATION\n")
            f.write(f"BASE_URL={server_url}\n\n")
        
        # Communication Channel
        channel_type = config_data.get('channel_type', 'telegram')
        f.write("# COMMUNICATION CHANNEL\n")
        f.write(f"CHANNEL_TYPE={channel_type}\n")
        
        if channel_type == 'telegram':
            f.write(f"TELEGRAM_BOT_TOKEN={config_data.get('telegram_token', '')}\n\n")
        elif channel_type == 'twilio':
            f.write(f"TWILIO_ACCOUNT_SID={config_data.get('twilio_sid', '')}\n")
            f.write(f"TWILIO_AUTH_TOKEN={config_data.get('twilio_token', '')}\n")
            f.write(f"TWILIO_PHONE_NUMBER={config_data.get('twilio_number', '')}\n\n")
        elif channel_type == 'sip':
            f.write(f"SIP_DOMAIN={config_data.get('sip_domain', '')}\n")
            f.write(f"SIP_USERNAME={config_data.get('sip_username', '')}\n")
            f.write(f"SIP_PASSWORD={config_data.get('sip_password', '')}\n\n")
        
        # SaaS Platform
        enable_saas = config_data.get('enable_saas', 'false')
        f.write("# SAAS PLATFORM (MULTI-TENANT)\n")
        f.write(f"ENABLE_SAAS={enable_saas}\n")
        if enable_saas == 'true':
            postgres_password = config_data.get('postgres_password') or secrets.token_urlsafe(16)
            admin_password = config_data.get('admin_password') or secrets.token_urlsafe(16)
            f.write(f"POSTGRES_PASSWORD={postgres_password}\n")
            f.write(f"ADMIN_PASSWORD={admin_password}\n")
        f.write("\n")
        
        # AI Model-specific configs
        deployment = ai_model
        
        if deployment == 'local':
            f.write("# LOCAL AI MODELS\n")
            f.write(f"OLLAMA_MODEL={config_data.get('ollama_model', 'tinyllama')}\n")
            f.write(f"WHISPER_MODEL={config_data.get('whisper_model', 'base')}\n\n")
        
        elif deployment == 'aws':
            f.write("# AWS CONFIGURATION\n")
            f.write(f"AWS_ACCESS_KEY_ID={config_data.get('aws_access_key', '')}\n")
            f.write(f"AWS_SECRET_ACCESS_KEY={config_data.get('aws_secret_key', '')}\n")
            f.write(f"AWS_REGION={config_data.get('aws_region', 'us-east-1')}\n")
            f.write(f"AWS_BEDROCK_MODEL={config_data.get('aws_bedrock_model', 'anthropic.claude-3-sonnet-20240229-v1:0')}\n\n")
        
        elif deployment == 'openai':
            f.write("# OPENAI CONFIGURATION\n")
            f.write(f"OPENAI_API_KEY={config_data.get('openai_api_key', '')}\n")
            f.write(f"OPENAI_MODEL={config_data.get('openai_model', 'gpt-4')}\n\n")

@app.route('/')
def index():
    """Main setup page"""
    current_config = load_current_config()
    return render_template('setup_index.html', config=current_config)

@app.route('/api/config', methods=['GET'])
def get_config():
    """Get current configuration"""
    return jsonify(load_current_config())

@app.route('/api/config', methods=['POST'])
def save_config_api():
    """Save configuration"""
    try:
        config_data = request.json
        save_config(config_data)
        
        # Generate nginx config if BASE_URL is provided
        if config_data.get('server_url'):
            try:
                result = subprocess.run(
                    ['bash', 'scripts/generate_nginx_config.sh'],
                    cwd='/mnt/e/call_center_agent',
                    capture_output=True,
                    text=True,
                    timeout=10
                )
                # Nginx config generation is optional, don't fail if it errors
                if result.returncode == 0:
                    print(f"✅ Nginx config generated: {result.stdout}")
            except Exception as nginx_error:
                print(f"⚠️  Nginx config generation failed: {nginx_error}")
        
        return jsonify({'success': True, 'message': 'Configuration saved successfully'})
    except Exception as e:
        return jsonify({'success': False, 'error': str(e)}), 500

@app.route('/api/deploy', methods=['POST'])
def deploy():
    """Deploy the selected configuration"""
    try:
        data = request.json
        ai_model = data.get('ai_model', 'local')
        enable_saas = data.get('enable_saas', 'false')
        
        # Save config first
        save_config(data)
        
        # Determine deployment command
        if enable_saas == 'true':
            # Deploy with SaaS platform
            cmd = f"cd /mnt/e/call_center_agent/deployments/saas && AI_MODEL={ai_model} ./setup.sh"
        else:
            # Deploy single tenant
            cmd = f"make {ai_model}"
        
        result = subprocess.run(cmd, shell=True, capture_output=True, text=True, cwd='/mnt/e/call_center_agent')
        
        if result.returncode == 0:
            deployment_name = f"{ai_model.upper()} + SaaS Platform" if enable_saas == 'true' else ai_model.upper()
            return jsonify({
                'success': True, 
                'message': f'{deployment_name} deployment started successfully!',
                'output': result.stdout
            })
        else:
            return jsonify({
                'success': False, 
                'error': result.stderr or result.stdout
            }), 500
            
    except Exception as e:
        return jsonify({'success': False, 'error': str(e)}), 500

@app.route('/api/test', methods=['POST'])
def test_config():
    """Test configuration (validate credentials)"""
    try:
        data = request.json
        ai_model = data.get('ai_model')
        channel_type = data.get('channel_type')
        errors = []
        
        # Validate channel
        if channel_type == 'telegram' and not data.get('telegram_token'):
            errors.append('Telegram bot token is required')
        elif channel_type == 'twilio':
            if not data.get('twilio_sid'):
                errors.append('Twilio Account SID is required')
            if not data.get('twilio_token'):
                errors.append('Twilio Auth Token is required')
        elif channel_type == 'sip':
            if not data.get('sip_domain'):
                errors.append('SIP Domain is required')
            if not data.get('sip_username'):
                errors.append('SIP Username is required')
        
        # Validate AI model configs
        if ai_model == 'aws':
            if not data.get('aws_access_key'):
                errors.append('AWS Access Key is required')
            if not data.get('aws_secret_key'):
                errors.append('AWS Secret Key is required')
        
        elif ai_model == 'openai':
            if not data.get('openai_api_key'):
                errors.append('OpenAI API Key is required')
        
        if errors:
            return jsonify({'success': False, 'errors': errors}), 400
        
        return jsonify({'success': True, 'message': 'Configuration looks good!'})
        
    except Exception as e:
        return jsonify({'success': False, 'error': str(e)}), 500

@app.route('/api/status', methods=['GET'])
def status():
    """Get deployment status"""
    try:
        result = subprocess.run('docker ps --format "{{.Names}}: {{.Status}}"', 
                              shell=True, capture_output=True, text=True)
        containers = result.stdout.strip().split('\n') if result.stdout.strip() else []
        
        return jsonify({
            'running': len(containers) > 0,
            'containers': containers
        })
    except Exception as e:
        return jsonify({'error': str(e)}), 500

if __name__ == '__main__':
    print("\n" + "="*60)
    print("🌐 AI Customer Care Agent - Web Setup UI")
    print("="*60)
    print(f"\n✅ Server starting on http://localhost:8080")
    print(f"✅ Open your browser to configure and deploy\n")
    print("Press Ctrl+C to stop the server\n")
    
    app.run(host='0.0.0.0', port=8080, debug=False)
